/**
 * NAVS TECHNO-VOC question bank: 20 questions per track (10 pre-skilled + 10 aptitude).
 * Exam draws 10 random per track → 110 items total across 11 courses.
 */

/** @typedef {{ q: string, type: 'pre-skilled'|'aptitude', options: [string,string,string,string], correct: 0|1|2|3 }} Item */

/** @type {Record<string, Item[]>} */
export const NAVS_QUESTION_BANK = {
  Automotive: [
    { type: "pre-skilled", q: "What does PPE stand for in an automotive workshop?", options: ["Personal Protective Equipment", "Power Performance Engine", "Primary Process Evaluation", "Portable Pump Equipment"], correct: 0 },
    { type: "pre-skilled", q: "Which tool is used to measure spark plug gap?", options: ["Torque wrench", "Feeler gauge", "Dial indicator", "Micrometer"], correct: 1 },
    { type: "pre-skilled", q: "Engine oil is primarily used to:", options: ["Cool the battery", "Lubricate moving parts", "Increase fuel octane", "Clean the exhaust"], correct: 1 },
    { type: "pre-skilled", q: "A dead battery is often first checked with a:", options: ["Compression tester", "Multimeter", "Timing light", "Vacuum gauge"], correct: 1 },
    { type: "pre-skilled", q: "Brake fluid should be handled carefully because it:", options: ["Freezes easily", "Can damage painted surfaces", "Conducts electricity", "Evaporates instantly"], correct: 1 },
    { type: "pre-skilled", q: "The firing order is found in the:", options: ["Tire sidewall", "Service manual or label", "Oil filter cap", "Radiator hose"], correct: 1 },
    { type: "pre-skilled", q: "Wheel lug nuts are tightened in a pattern to:", options: ["Save time", "Distribute clamping evenly", "Reduce tire wear only", "Align the camshaft"], correct: 1 },
    { type: "pre-skilled", q: "A timing belt connects the crankshaft to the:", options: ["Alternator only", "Camshaft", "Steering rack", "Fuel pump only"], correct: 1 },
    { type: "pre-skilled", q: "Coolant overflow tank level is checked when the engine is:", options: ["At operating temperature or cool per manual", "Revving at 3000 RPM", "Removed from the bay", "Running with AC off only"], correct: 0 },
    { type: "pre-skilled", q: "An OBD-II scanner is used to:", options: ["Balance tires", "Read diagnostic trouble codes", "Measure bore diameter", "Adjust headlight aim only"], correct: 1 },
    { type: "aptitude", q: "If 4 tires cost 3200 pesos each, what is the total?", options: ["9600 pesos", "12800 pesos", "11200 pesos", "10800 pesos"], correct: 1 },
    { type: "aptitude", q: "A workshop rule says 'lift heavy parts with your legs.' This mainly prevents:", options: ["Eye strain", "Back injury", "Hearing loss", "Sunburn"], correct: 1 },
    { type: "aptitude", q: "Oil label 10W-40: the number 40 refers to viscosity at:", options: ["Cold start only", "High operating temperature", "Idle RPM only", "Battery voltage"], correct: 1 },
    { type: "aptitude", q: "A car travels 60 km in 1 hour. Its average speed is:", options: ["30 km/h", "60 km/h", "90 km/h", "120 km/h"], correct: 1 },
    { type: "aptitude", q: "Which sequence is safest when jacking a vehicle?", options: ["Jack first, then chock wheels", "Park on level ground, engage brake, chock wheels, then jack", "Remove wheels before jacking", "Jack on a slope for access"], correct: 1 },
    { type: "aptitude", q: "If resistance increases in a circuit, current will generally:", options: ["Always double", "Decrease if voltage is constant", "Stay unchanged", "Become zero always"], correct: 1 },
    { type: "aptitude", q: "A technician reads 'RTV' on a gasket procedure. They should:", options: ["Skip the step", "Follow the manual for sealant use", "Use only tape", "Overtighten bolts"], correct: 1 },
    { type: "aptitude", q: "Half of 48 bolt sets is:", options: ["20", "24", "28", "36"], correct: 1 },
    { type: "aptitude", q: "Gasoline vapor is dangerous mainly because it is:", options: ["Heavy and sinks", "Flammable", "Radioactive", "Always visible"], correct: 1 },
    { type: "aptitude", q: "Choosing the correct wrench size first helps avoid:", options: ["Better fuel economy", "Rounded fasteners and injury", "Paint fading", "Radio interference"], correct: 1 },
  ],
  Agriculture: [
    { type: "pre-skilled", q: "Composting improves soil by adding:", options: ["Plastic mulch", "Organic matter", "Salt", "Cement"], correct: 1 },
    { type: "pre-skilled", q: "A hand trowel is mainly used for:", options: ["Harvesting rice", "Transplanting seedlings", "Ploughing fields", "Irrigation pumping"], correct: 1 },
    { type: "pre-skilled", q: "Integrated Pest Management (IPM) emphasizes:", options: ["Only chemical sprays", "Multiple control methods", "Ignoring pests", "Burning all crops"], correct: 1 },
    { type: "pre-skilled", q: "NPK fertilizer provides:", options: ["Nitrogen, phosphorus, potassium", "Nickel, platinum, krypton", "Neon, phosphorus, kelp", "Nitrogen only"], correct: 0 },
    { type: "pre-skilled", q: "Crop rotation helps reduce:", options: ["Soil building", "Pest and disease buildup", "Sunlight", "Rainfall"], correct: 1 },
    { type: "pre-skilled", q: "Drip irrigation saves water by:", options: ["Flooding the field", "Delivering water near roots", "Spraying leaves only at noon", "Using salt water"], correct: 1 },
    { type: "pre-skilled", q: "A greenhouse primarily:", options: ["Blocks all light", "Controls temperature and humidity", "Replaces soil", "Stores gasoline"], correct: 1 },
    { type: "pre-skilled", q: "Hybrid seeds are produced by:", options: ["Crossing selected parent lines", "Freezing seeds", "Adding dye", "Drying in sunlight only"], correct: 0 },
    { type: "pre-skilled", q: "Soil pH affects:", options: ["Only seed color", "Nutrient availability to plants", "Wind speed", "Tractor horsepower"], correct: 1 },
    { type: "pre-skilled", q: "Harvesting leafy vegetables in the cool morning helps:", options: ["Increase wilting", "Maintain freshness", "Kill all pests instantly", "Remove soil permanently"], correct: 1 },
    { type: "aptitude", q: "A plot is 10 m by 5 m. Its area is:", options: ["15 m²", "50 m²", "25 m²", "100 m²"], correct: 1 },
    { type: "aptitude", q: "If 8 workers finish a task in 6 hours, more workers (same skill) will usually:", options: ["Take longer", "Finish sooner", "Change soil pH", "Stop rain"], correct: 1 },
    { type: "aptitude", q: "Reading a weather forecast before spraying pesticides helps avoid:", options: ["Better yields always", "Drift and wash-off from rain", "Seed germination only", "Soil compaction"], correct: 1 },
    { type: "aptitude", q: "25% of 200 kg harvest is:", options: ["40 kg", "50 kg", "75 kg", "100 kg"], correct: 1 },
    { type: "aptitude", q: "Overwatering seedlings often causes:", options: ["Faster photosynthesis only", "Root rot and poor growth", "Instant flowering", "Higher oil content"], correct: 1 },
    { type: "aptitude", q: "A farmer tests soil before planting to:", options: ["Choose paint color", "Decide amendments and crops", "Measure wind", "Fix engines"], correct: 1 },
    { type: "aptitude", q: "Storing chemicals in labeled containers prevents:", options: ["Photosynthesis", "Misuse and poisoning", "Rain", "Pollination"], correct: 1 },
    { type: "aptitude", q: "3 rows with 40 plants each have how many plants?", options: ["43", "80", "120", "160"], correct: 2 },
    { type: "aptitude", q: "Beneficial insects in a farm ecosystem can:", options: ["Destroy all crops", "Help control pests naturally", "Replace water", "Increase gasoline use"], correct: 1 },
    { type: "aptitude", q: "Mulching conserves moisture by:", options: ["Heating soil surface", "Reducing evaporation", "Blocking all air", "Adding salt"], correct: 1 },
  ],
  "Beauty Care": [
    { type: "pre-skilled", q: "Sanitation in a salon prevents:", options: ["Hair growth", "Cross-infection", "Client relaxation only", "Product evaporation"], correct: 1 },
    { type: "pre-skilled", q: "A patch test checks for:", options: ["Hair length", "Allergic reaction to products", "Nail hardness only", "Scalp temperature"], correct: 1 },
    { type: "pre-skilled", q: "Shampoo is applied to:", options: ["Dry painted walls", "Scalp and hair", "Metal tools only", "Client shoes"], correct: 1 },
    { type: "pre-skilled", q: "Sterilizing metal implements commonly uses:", options: ["Plain water only", "Approved disinfectant or autoclave", "Perfume", "Hair spray"], correct: 1 },
    { type: "pre-skilled", q: "Hair porosity refers to:", options: ["Hair color brand", "Ability to absorb moisture", "Scissors sharpness", "Chair height"], correct: 1 },
    { type: "pre-skilled", q: "A concave hairbrush helps create:", options: ["Flat iron rust", "Curl and volume when blow-drying", "Nail polish", "Skin peels"], correct: 1 },
    { type: "pre-skilled", q: "Facial cleansing removes:", options: ["Bone structure", "Surface dirt and excess oil", "All melanin permanently", "Client consent"], correct: 1 },
    { type: "pre-skilled", q: "Manicure cuticle work should be:", options: ["Aggressive tearing", "Gentle and hygienic", "Done with dirty tools", "Skipped always"], correct: 1 },
    { type: "pre-skilled", q: "Hair color levels range from dark to light; level 1 is:", options: ["Lightest blonde", "Darkest", "Medium brown only", "Clear"], correct: 1 },
    { type: "pre-skilled", q: "Client consultation records help track:", options: ["Weather only", "Services, allergies, and formulas", "Floor tiles", "Parking fees"], correct: 1 },
    { type: "aptitude", q: "Mixing 1 part developer with 2 parts color means ratio:", options: ["1:2", "2:1", "1:1 only", "3:0"], correct: 0 },
    { type: "aptitude", q: "A client reports burning during a chemical service. You should:", options: ["Continue quickly", "Stop and rinse per safety protocol", "Add more product", "Use hotter water"], correct: 1 },
    { type: "aptitude", q: "If a service takes 45 minutes and starts at 2:00 PM, it ends at:", options: ["2:30 PM", "2:45 PM", "3:00 PM", "3:15 PM"], correct: 1 },
    { type: "aptitude", q: "Double-processing hair without assessment risks:", options: ["Better shine only", "Damage and breakage", "Faster nail growth", "Lower room temperature"], correct: 1 },
    { type: "aptitude", q: "20% discount on a 500 peso service saves:", options: ["50 pesos", "100 pesos", "150 pesos", "200 pesos"], correct: 1 },
    { type: "aptitude", q: "Wearing gloves during hair color application mainly protects:", options: ["Client shoes", "Your skin from chemicals", "Mirrors", "Music volume"], correct: 1 },
    { type: "aptitude", q: "Organizing tools before a client arrives improves:", options: ["Soil fertility", "Efficiency and professionalism", "Engine torque", "Crop yield"], correct: 1 },
    { type: "aptitude", q: "A strand test before full color helps predict:", options: ["Client height", "Result and damage risk", "Wind direction", "Tax rate"], correct: 1 },
    { type: "aptitude", q: "Ventilation in a chemical service area reduces:", options: ["Hair count", "Fume buildup", "Water pressure", "Nail length"], correct: 1 },
    { type: "aptitude", q: "Three clients at 30 minutes each need at least:", options: ["30 minutes total", "90 minutes total", "60 minutes total", "15 minutes total"], correct: 1 },
  ],
  Carpentry: [
    { type: "pre-skilled", q: "A try square is used to mark:", options: ["Curved arcs only", "90-degree angles", "Pipe threads", "Electrical loads"], correct: 1 },
    { type: "pre-skilled", q: "Pilot holes before screwing help prevent:", options: ["Better paint", "Wood splitting", "Metal rust only", "Glass cutting"], correct: 1 },
    { type: "pre-skilled", q: "Plywood grain direction affects:", options: ["Nothing", "Strength and appearance", "Battery life", "Water boiling point"], correct: 1 },
    { type: "pre-skilled", q: "A claw hammer is used for:", options: ["Welding aluminum", "Driving and removing nails", "Mixing concrete by hand only", "Soldering wires"], correct: 1 },
    { type: "pre-skilled", q: "Wood moisture content should be appropriate to avoid:", options: ["Better glue only", "Warping and shrinkage", "Louder music", "Faster internet"], correct: 1 },
    { type: "pre-skilled", q: "A chisel should be struck with:", options: ["A wooden mallet or hammer on handle end properly", "Any rock", "A welding torch", "Paint brush"], correct: 0 },
    { type: "pre-skilled", q: "Level tool bubble centered means surface is:", options: ["Magnetic", "Horizontal or vertical as intended", "Underwater", "Radioactive"], correct: 1 },
    { type: "pre-skilled", q: "Countersink bit allows screw head to:", options: ["Stick out more", "Sit flush or below surface", "Melt plastic", "Conduct AC power"], correct: 1 },
    { type: "pre-skilled", q: "Safety goggles protect against:", options: ["Only sunburn", "Flying chips and dust", "Loud sounds only", "Weight gain"], correct: 1 },
    { type: "pre-skilled", q: "Measuring twice before cutting helps:", options: ["Waste material and errors", "Increase humidity", "Change voltage", "Grow plants"], correct: 0 },
    { type: "aptitude", q: "Board length 2.4 m cut into 4 equal pieces: each piece is:", options: ["0.4 m", "0.6 m", "0.8 m", "1.2 m"], correct: 1 },
    { type: "aptitude", q: "If 3 workers need 12 hours, 6 equal workers need about:", options: ["24 hours", "6 hours", "12 hours", "3 hours"], correct: 1 },
    { type: "aptitude", q: "Diagonal of a square frame checks if corners are:", options: ["Round", "Square", "Wet", "Magnetic"], correct: 1 },
    { type: "aptitude", q: "Saw blade teeth pointing wrong direction will:", options: ["Cut faster always", "Cut poorly or dangerously", "Polish metal", "Pump water"], correct: 1 },
    { type: "aptitude", q: "15% of 2000 pesos material cost is:", options: ["200 pesos", "300 pesos", "350 pesos", "400 pesos"], correct: 1 },
    { type: "aptitude", q: "Extension cord on floor in workshop is a:", options: ["Good storage", "Trip hazard", "Measuring tool", "Clamp"], correct: 1 },
    { type: "aptitude", q: "Choosing harder wood for legs and softer for panels is:", options: ["Random", "Matching properties to use", "Illegal", "Only for metal"], correct: 1 },
    { type: "aptitude", q: "2.5 cm is equal to:", options: ["25 mm", "250 mm", "0.25 mm", "2.5 m"], correct: 0 },
    { type: "aptitude", q: "Reading a blueprint scale 1:10 means drawing 1 cm equals:", options: ["1 cm real", "10 cm real", "10 m always", "1 mm real"], correct: 1 },
    { type: "aptitude", q: "Clamping glued joints until dry prevents:", options: ["Strong bond", "Weak misaligned bond", "Paint color change", "Electrical short"], correct: 1 },
  ],
  Dressmaking: [
    { type: "pre-skilled", q: "Grain line on a pattern aligns with:", options: ["Bias only always", "Lengthwise fabric grain", "Zipper teeth", "Buttonholes randomly"], correct: 1 },
    { type: "pre-skilled", q: "A seam allowance is:", options: ["Extra fabric beyond the seam line", "The needle only", "Thread color", "Iron temperature"], correct: 0 },
    { type: "pre-skilled", q: "Pink shears help reduce:", options: ["Electric bills", "Fabric fraying", "Pattern size", "Client height"], correct: 1 },
    { type: "pre-skilled", q: "Basting stitches are:", options: ["Permanent decorative only", "Temporary holding stitches", "For welding", "Electrical grounds"], correct: 1 },
    { type: "pre-skilled", q: "A zipper foot on a machine helps sew:", options: ["Only straight hems far from zipper", "Close to zipper coils", "Metal pipes", "Food products"], correct: 1 },
    { type: "pre-skilled", q: "Natural fiber examples include:", options: ["Polyester only", "Cotton and linen", "PVC", "Nylon only"], correct: 1 },
    { type: "pre-skilled", q: "Pressing seams open with iron:", options: ["Melts all fabric always", "Sets stitches flat for finish", "Replaces sewing", "Cuts patterns"], correct: 1 },
    { type: "pre-skilled", q: "Taking body measurements should be done:", options: ["Over bulky coat always", "Snug and consistent", "Without tape", "Only after cutting"], correct: 1 },
    { type: "pre-skilled", q: "Notches on patterns mark:", options: ["Fabric price", "Matching points", "Thread brand", "Machine oil"], correct: 1 },
    { type: "pre-skilled", q: "A serger (overlock) mainly:", options: ["Cuts wood", "Finishes edges and prevents fray", "Pumps water", "Tests voltage"], correct: 1 },
    { type: "aptitude", q: "Fabric is 150 cm wide and you need 3 m length. Area used is:", options: ["150 sq cm", "4.5 sq m", "450 sq cm", "0.45 sq m"], correct: 1 },
    { type: "aptitude", q: "If waist is 70 cm and ease is 2 cm, minimum band is:", options: ["68 cm", "72 cm", "140 cm", "35 cm"], correct: 1 },
    { type: "aptitude", q: "Sewing machine needle too large for thin fabric may:", options: ["Improve drape", "Leave holes and puckers", "Change color", "Balance tires"], correct: 1 },
    { type: "aptitude", q: "25% extra fabric for matching plaids means buy:", options: ["Less fabric", "1.25 times calculated amount", "No pattern", "Only thread"], correct: 1 },
    { type: "aptitude", q: "Client wants hem 5 cm shorter on skirt. You measure from:", options: ["Ceiling", "Existing hem or marked line", "Other person's shoe", "Machine serial"], correct: 1 },
    { type: "aptitude", q: "Thread tension too tight causes:", options: ["Loose balanced stitches", "Puckering and breakage", "Better stretch always", "Metal rust"], correct: 1 },
    { type: "aptitude", q: "Converting 1 inch ≈ 2.54 cm means 10 inches is about:", options: ["25.4 cm", "10 cm", "5.4 cm", "100 cm"], correct: 0 },
    { type: "aptitude", q: "Laying pattern on fold saves fabric by:", options: ["Cutting two halves at once symmetrically", "Using more scraps randomly", "Skipping seams", "Burning edges"], correct: 0 },
    { type: "aptitude", q: "A stain on white fabric before construction should be:", options: ["Ignored", "Treated or fabric replaced", "Painted over", "Welded"], correct: 1 },
    { type: "aptitude", q: "Schedule: 2 hours cutting + 4 hours sewing = total:", options: ["5 hours", "6 hours", "8 hours", "2 hours"], correct: 1 },
  ],
  Drafting: [
    { type: "pre-skilled", q: "A scale ruler on drawings shows:", options: ["Real-world proportion reduced", "Paint color", "Music tempo", "Battery amps"], correct: 0 },
    { type: "pre-skilled", q: "Hidden lines in orthographic views represent:", options: ["Visible edges only", "Features not seen in that view", "Title block", "North arrow only"], correct: 1 },
    { type: "pre-skilled", q: "CAD stands for:", options: ["Computer-Aided Design", "Central Air Duct", "Chemical Analysis Device", "Cut And Drill"], correct: 0 },
    { type: "pre-skilled", q: "First-angle vs third-angle projection differs in:", options: ["Paper color", "Placement of views", "Thread type", "Soil pH"], correct: 1 },
    { type: "pre-skilled", q: "A compass draws:", options: ["Square only", "Circles and arcs", "3D prints", "Welds only"], correct: 1 },
    { type: "pre-skilled", q: "Dimension lines should have:", options: ["No units", "Clear arrows and numeric size", "Only colors", "Random angles"], correct: 1 },
    { type: "pre-skilled", q: "Section view shows:", options: ["Interior as if cut", "Only exterior paint", "Client name", "Zip code"], correct: 0 },
    { type: "pre-skilled", q: "Title block typically includes:", options: ["Recipe", "Drawing name, scale, date", "Hair color", "Tire pressure"], correct: 1 },
    { type: "pre-skilled", q: "Lettering on technical drawings should be:", options: ["Illegible", "Legible and consistent", "Only cursive", "Invisible"], correct: 1 },
    { type: "pre-skilled", q: "An isometric drawing shows:", options: ["One face only flat", "3D on 2D with parallel axes", "Soil layers", "Circuit amps only"], correct: 1 },
    { type: "aptitude", q: "Scale 1:50 means 1 cm on paper equals:", options: ["1 cm real", "50 cm real", "50 m always", "5 mm real"], correct: 1 },
    { type: "aptitude", q: "Room 4 m × 3 m floor area is:", options: ["7 m²", "12 m²", "14 m²", "1.33 m²"], correct: 1 },
    { type: "aptitude", q: "If north arrow rotates, views should:", options: ["Stay consistent with orientation", "Delete dimensions", "Change scale randomly", "Remove title"], correct: 0 },
    { type: "aptitude", q: "Converting 5000 mm to meters:", options: ["0.5 m", "5 m", "50 m", "500 m"], correct: 1 },
    { type: "aptitude", q: "Overlapping dimension lines cause:", options: ["Clear reading", "Confusion and errors", "Better welding", "Faster haircuts"], correct: 1 },
    { type: "aptitude", q: "Checking a print against site measurements prevents:", options: ["Accurate construction", "Costly field mistakes", "Better soil", "Nail polish"], correct: 1 },
    { type: "aptitude", q: "Half of 90 degrees is:", options: ["30°", "45°", "60°", "180°"], correct: 1 },
    { type: "aptitude", q: "Revision cloud on a drawing indicates:", options: ["Deleted building", "Changed area", "North pole", "Food zone"], correct: 1 },
    { type: "aptitude", q: "Layer standards in CAD help:", options: ["Hide organization", "Organize object types", "Remove scale", "Block internet"], correct: 1 },
    { type: "aptitude", q: "A wall drawn 6 mm thick at 1:100 represents:", options: ["6 mm real", "600 mm real", "6 m real", "60 m real"], correct: 1 },
  ],
  Electricity: [
    { type: "pre-skilled", q: "The unit of electric current is:", options: ["Volt", "Ampere", "Ohm", "Watt"], correct: 1 },
    { type: "pre-skilled", q: "A circuit breaker protects by:", options: ["Increasing voltage always", "Opening when current is excessive", "Storing water", "Cooling motors only"], correct: 1 },
    { type: "pre-skilled", q: "Green or green-yellow wire is typically:", options: ["Live/hot", "Ground/earth", "Neutral only in all countries", "Data line"], correct: 1 },
    { type: "pre-skilled", q: "Ohm's law relates:", options: ["V, I, R", "Weight, mass, volume", "Heat, light, sound only", "RPM, torque, HP only"], correct: 0 },
    { type: "pre-skilled", q: "Before working on a panel you should:", options: ["Wet hands help", "Lock-out / tag-out and verify dead", "Use metal ladder in rain", "Skip PPE"], correct: 1 },
    { type: "pre-skilled", q: "A multimeter can measure:", options: ["Hair length", "Voltage and resistance", "Soil taste", "Paint viscosity"], correct: 1 },
    { type: "pre-skilled", q: "Series circuit current is:", options: ["Different in each branch always", "Same through each component", "Zero always", "Only AC"], correct: 1 },
    { type: "pre-skilled", q: "Conduit protects:", options: ["Only wood", "Wires from damage", "Client hair", "Crop roots"], correct: 1 },
    { type: "pre-skilled", q: "AC means current:", options: ["Stays constant direction", "Reverses direction periodically", "Stops forever", "Only in batteries"], correct: 1 },
    { type: "pre-skilled", q: "Wire gauge number: lower number means:", options: ["Thinner wire", "Thicker wire", "No copper", "Higher resistance always"], correct: 1 },
    { type: "aptitude", q: "Power 1200 W at 240 V draws current:", options: ["2 A", "5 A", "10 A", "0.5 A"], correct: 1 },
    { type: "aptitude", q: "Water near energized equipment increases risk of:", options: ["Better insulation", "Electric shock", "Lower bill only", "Faster sewing"], correct: 1 },
    { type: "aptitude", q: "Three 100 W bulbs in parallel on 220 V each get:", options: ["Less than rated voltage each", "Full line voltage across each", "No current", "Only DC"], correct: 1 },
    { type: "aptitude", q: "Resistance 10 Ω at 5 V gives current:", options: ["0.5 A", "2 A", "50 A", "15 A"], correct: 0 },
    { type: "aptitude", q: "Reading wiring diagram before install helps:", options: ["Skip grounding", "Correct connections", "Remove breakers", "Paint walls"], correct: 1 },
    { type: "aptitude", q: "If tool cord is frayed you should:", options: ["Tape and use forever", "Replace or repair before use", "Wet it", "Share one glove"], correct: 1 },
    { type: "aptitude", q: "kWh measures:", options: ["Energy consumed over time", "Speed only", "Pressure", "Length"], correct: 0 },
    { type: "aptitude", q: "Polarity matters for:", options: ["Incandescent bulb only always", "LED and electronic loads often", "Wooden desk", "Cotton shirt"], correct: 1 },
    { type: "aptitude", q: "Doubling voltage across fixed resistor doubles:", options: ["Resistance", "Current", "Mass", "Thread count"], correct: 1 },
    { type: "aptitude", q: "GFCI/RCD devices detect:", options: ["Hair color", "Ground fault leakage", "Wind speed", "Fabric grain"], correct: 1 },
  ],
  Electronics: [
    { type: "pre-skilled", q: "A resistor limits:", options: ["Water flow", "Electric current", "Sound only", "Gravity"], correct: 1 },
    { type: "pre-skilled", q: "Capacitor stores:", options: ["Mechanical energy", "Electrical charge", "Wood chips", "Paint"], correct: 1 },
    { type: "pre-skilled", q: "LED polarity means:", options: ["No direction matters ever", "Anode and cathode must be correct", "Only AC works", "It is a motor"], correct: 1 },
    { type: "pre-skilled", q: "Soldering iron tip should be:", options: ["Dirty and cold", "Clean and properly tinned", "Used on live mains always", "Dipped in oil"], correct: 1 },
    { type: "pre-skilled", q: "Breadboard is used for:", options: ["Cutting bread only", "Prototype circuits without soldering", "Welding steel", "Mixing dye"], correct: 1 },
    { type: "pre-skilled", q: "Transistor can act as:", options: ["Only heater", "Switch or amplifier", "Hammer", "Ruler"], correct: 1 },
    { type: "pre-skilled", q: "Digital logic 1 and 0 represent:", options: ["High and low voltage states", "Hot and cold water", "Day and night only", "Weight units"], correct: 0 },
    { type: "pre-skilled", q: "Oscilloscope displays:", options: ["Voltage over time", "Hair length", "Soil pH paper color", "Tire tread"], correct: 0 },
    { type: "pre-skilled", q: "ESD strap prevents:", options: ["All learning", "Static damage to sensitive ICs", "Better cooking", "Louder music"], correct: 1 },
    { type: "pre-skilled", q: "Reading resistor color bands gives:", options: ["Resistance value", "Engine oil grade", "Fabric width", "Room area"], correct: 0 },
    { type: "aptitude", q: "Series resistors 100 Ω + 200 Ω total:", options: ["150 Ω", "300 Ω", "66 Ω", "20000 Ω"], correct: 1 },
    { type: "aptitude", q: "Reversed LED in simple circuit often:", options: ["Shines brighter", "Does not light", "Charges battery", "Cuts wood"], correct: 1 },
    { type: "aptitude", q: "If supply is 9 V and resistor 3 k ohms, current is about:", options: ["3 mA", "3 A", "27 A", "0 A always"], correct: 0 },
    { type: "aptitude", q: "Flux in soldering helps:", options: ["Rust metal", "Wet metal for good joint", "Insulate forever", "Block heat"], correct: 1 },
    { type: "aptitude", q: "Binary 1010 equals decimal:", options: ["8", "10", "12", "5"], correct: 1 },
    { type: "aptitude", q: "Overheating component smell means:", options: ["Normal always", "Stop power and inspect", "Add water", "Increase voltage"], correct: 1 },
    { type: "aptitude", q: "Parallel identical resistors halve total resistance when:", options: ["Two same value", "One only", "None", "Ten different"], correct: 0 },
    { type: "aptitude", q: "Datasheet shows max current to avoid:", options: ["Reading", "Burning out component", "Using PCB", "Labeling wires"], correct: 1 },
    { type: "aptitude", q: "Logic gate AND outputs 1 when:", options: ["Any input 0", "All inputs 1", "No power", "Random"], correct: 1 },
    { type: "aptitude", q: "Organizing wires by signal and power reduces:", options: ["Function", "Noise and mistakes", "Cost always to zero", "Screen size"], correct: 1 },
  ],
  "Food Tech": [
    { type: "pre-skilled", q: "HACCP focuses on:", options: ["Food safety hazards control", "Car engine tune-up", "Hair styling", "Welding rods"], correct: 0 },
    { type: "pre-skilled", q: "Cross-contamination is prevented by:", options: ["Same board for raw and cooked", "Separate utensils and surfaces", "Room temperature storage long term", "Skipping hand wash"], correct: 1 },
    { type: "pre-skilled", q: "Blanching vegetables briefly in boiling water helps:", options: ["Remove all nutrients always", "Set color and reduce enzymes", "Add bacteria", "Freeze metal"], correct: 1 },
    { type: "pre-skilled", q: "Mise en place means:", options: ["Everything in its place before cooking", "Burning food", "Selling only drinks", "Measuring voltage"], correct: 0 },
    { type: "pre-skilled", q: "Safe internal temperature for cooked chicken is about:", options: ["20 degrees C", "74 degrees C", "10 degrees C", "Room temperature only"], correct: 1 },
    { type: "pre-skilled", q: "Yeast in bread produces:", options: ["CO2 gas for leavening", "Metal rust", "Plastic", "AC current"], correct: 0 },
    { type: "pre-skilled", q: "Emulsion example is:", options: ["Oil and water mixed like mayonnaise", "Dry rice only", "Solid steel", "Empty pan"], correct: 0 },
    { type: "pre-skilled", q: "Refrigerator storage keeps food:", options: ["In danger zone longer", "Below bacterial rapid growth temps", "Hot always", "Frozen solid only"], correct: 1 },
    { type: "pre-skilled", q: "Knife sharpening steel realigns:", options: ["Engine piston", "Blade edge", "Circuit trace", "Pipe thread"], correct: 1 },
    { type: "pre-skilled", q: "Standardized recipes ensure:", options: ["Random taste each batch", "Consistent quality and cost control", "No measuring", "Only frying"], correct: 1 },
    { type: "aptitude", q: "A recipe serves 4 portions. You need 12 portions. Multiply ingredients by:", options: ["2", "3", "4", "0.5"], correct: 1 },
    { type: "aptitude", q: "Thawing frozen meat at room temperature for hours is:", options: ["Best practice", "Unsafe; use fridge or controlled methods", "Required for salad", "Same as cooking"], correct: 1 },
    { type: "aptitude", q: "250 mL is equal to:", options: ["0.25 L", "2.5 L", "25 L", "0.025 L"], correct: 0 },
    { type: "aptitude", q: "Bitter taste in burnt garlic means:", options: ["Perfect", "Overcooked; start again or adjust", "More sugar only fix", "Add oil to extinguish"], correct: 1 },
    { type: "aptitude", q: "If food costs 80 pesos and sells for 200 pesos, food cost percent is:", options: ["40%", "80%", "120%", "20%"], correct: 0 },
    { type: "aptitude", q: "Wet hands handling electrical kitchen equipment is:", options: ["Safe", "Hazardous", "Required", "Faster cooling"], correct: 1 },
    { type: "aptitude", q: "FIFO stock rotation means use:", options: ["Newest first", "Oldest first", "Random cans", "Expired first"], correct: 1 },
    { type: "aptitude", q: "Doubling a cake recipe may need:", options: ["Same pan time always", "Adjusted time and pan size", "No oven", "Half heat"], correct: 1 },
    { type: "aptitude", q: "Sanitizer concentration too weak will:", options: ["Kill all germs surely", "Fail to sanitize properly", "Improve flavor", "Weld pans"], correct: 1 },
    { type: "aptitude", q: "3 hours prep + 1 hour cook for event needs start:", options: ["1 hour before", "4 hours before service", "After eating", "Next day only"], correct: 1 },
  ],
  ICT: [
    { type: "pre-skilled", q: "CPU stands for:", options: ["Central Processing Unit", "Computer Personal Utility", "Cable Power Unit", "Central Print Upgrade"], correct: 0 },
    { type: "pre-skilled", q: "RAM is:", options: ["Permanent storage only", "Volatile memory for active tasks", "Monitor brand", "Printer ink"], correct: 1 },
    { type: "pre-skilled", q: "HTTPS indicates:", options: ["Unencrypted web", "Encrypted web traffic", "Offline mode", "Paper protocol"], correct: 1 },
    { type: "pre-skilled", q: "A router connects:", options: ["Only keyboards", "Networks and routes packets", "Welding torch", "Water pipes"], correct: 1 },
    { type: "pre-skilled", q: "Phishing is:", options: ["Fish cooking", "Trick to steal credentials", "Hardware upgrade", "Cable type"], correct: 1 },
    { type: "pre-skilled", q: "Backup copies data to:", options: ["Nowhere", "Secondary location or media", "Delete drive only", "RAM permanently"], correct: 1 },
    { type: "pre-skilled", q: "OS examples include:", options: ["Windows, Linux, macOS", "Only Microsoft Word", "HDMI cable", "Solder wire"], correct: 0 },
    { type: "pre-skilled", q: "Binary uses digits:", options: ["0 and 1", "1 to 9 only", "A to F only", "Colors"], correct: 0 },
    { type: "pre-skilled", q: "Spreadsheet cell A1 refers to:", options: ["Column A row 1", "Row A column 1", "Printer tray", "USB port"], correct: 0 },
    { type: "pre-skilled", q: "Strong password should be:", options: ["Your birthday", "Long, mixed, unique", "password123 for all sites", "Written on monitor"], correct: 1 },
    { type: "aptitude", q: "1 GB ≈ how many MB (decimal common use)?", options: ["100", "1000", "1024 in binary context often", "10"], correct: 2 },
    { type: "aptitude", q: "If download is 50 MB/s, 200 MB file takes about:", options: ["1 second", "4 seconds", "10 minutes", "1 hour"], correct: 1 },
    { type: "aptitude", q: "Opening unknown email attachment may:", options: ["Speed PC always", "Install malware", "Clean virus", "Fix Wi-Fi"], correct: 1 },
    { type: "aptitude", q: "IP address 192.168.1.10 is likely:", options: ["Public internet only", "Private local network", "GPS coordinate", "Temperature"], correct: 1 },
    { type: "aptitude", q: "Ctrl+S in most apps:", options: ["Deletes file", "Saves", "Shuts PC", "Formats disk"], correct: 1 },
    { type: "aptitude", q: "If 8 bits = 1 byte, 16 bits =", options: ["1 byte", "2 bytes", "16 bytes", "4 bytes"], correct: 1 },
    { type: "aptitude", q: "Cloud storage means files on:", options: ["Only floppy disk", "Remote servers accessible online", "Inside mouse", "Paper only"], correct: 1 },
    { type: "aptitude", q: "Troubleshoot no internet: logical first step:", options: ["Replace monitor", "Check cable/Wi-Fi and router", "Reinstall OS immediately", "Buy new chair"], correct: 1 },
    { type: "aptitude", q: "Version control (e.g. Git) helps:", options: ["Cook food", "Track code changes", "Paint walls", "Grow rice"], correct: 1 },
    { type: "aptitude", q: "Recycling e-waste properly prevents:", options: ["Better FPS", "Environmental harm", "Faster typing only", "Hair damage"], correct: 1 },
  ],
  SMAW: [
    { type: "pre-skilled", q: "SMAW stands for:", options: ["Shielded Metal Arc Welding", "Soft Metal Assembly Work", "Standard Motor Air Wiring", "Steel Measure And Weld"], correct: 0 },
    { type: "pre-skilled", q: "Welding helmet protects from:", options: ["Only rain", "Arc flash and sparks", "Sound only", "Paper cuts"], correct: 1 },
    { type: "pre-skilled", q: "Electrode coating provides:", options: ["Shielding gas and slag", "Paint color only", "Fuel for engine", "Coolant for PC"], correct: 0 },
    { type: "pre-skilled", q: "Work clamp (ground) attaches to:", options: ["Electrode holder only", "Workpiece or table", "Helmet", "Water hose"], correct: 1 },
    { type: "pre-skilled", q: "Arc length should generally be:", options: ["Very long", "About equal to electrode diameter", "Zero", "One meter"], correct: 1 },
    { type: "pre-skilled", q: "Slag after welding should be:", options: ["Left forever", "Removed after cooling", "Eaten", "Poured in fuel tank"], correct: 1 },
    { type: "pre-skilled", q: "6013 electrode is often used for:", options: ["Underwater only", "General purpose mild steel", "Wood joinery", "Hair coloring"], correct: 1 },
    { type: "pre-skilled", q: "Ventilation during welding reduces:", options: ["Skill", "Fume inhalation risk", "Arc visibility always", "Metal strength always"], correct: 1 },
    { type: "pre-skilled", q: "Polarity affects:", options: ["Only paint", "Penetration and bead shape", "Soil pH", "Thread count"], correct: 1 },
    { type: "pre-skilled", q: "Hot metal after welding should be:", options: ["Touched to test", "Marked hot and cooled safely", "Sprayed with water on hot weld always", "Hidden under paper"], correct: 1 },
    { type: "aptitude", q: "Welding near flammable liquids is:", options: ["Safe", "Extremely dangerous", "Required", "Good for speed"], correct: 1 },
    { type: "aptitude", q: "If machine shows 120 A and duty cycle 20%, long welds need:", options: ["No breaks ever", "Cool-down periods", "Higher amps only", "Remove ground"], correct: 1 },
    { type: "aptitude", q: "Distortion in thin plate can be reduced by:", options: ["More heat everywhere", "Tack welds and balanced sequence", "Skip PPE", "Faster travel only always"], correct: 1 },
    { type: "aptitude", q: "Oily metal before weld should be:", options: ["Left as is", "Cleaned", "Painted thick", "Wet with soap"], correct: 1 },
    { type: "aptitude", q: "Welding galvanized steel without proper protection risks:", options: ["Better beads only", "Toxic fume exposure", "Lower amps always", "No hazard"], correct: 1 },
    { type: "aptitude", q: "Two 3 mm plates lap joint: electrode size often near:", options: ["1 mm only", "3.2 mm class common", "20 mm", "0.5 mm"], correct: 1 },
    { type: "aptitude", q: "Fire extinguisher type for electrical fire class (check label) often:", options: ["Water only always", "CO2 or dry chemical suitable", "Cooking oil only", "Paper only"], correct: 1 },
    { type: "aptitude", q: "Travel speed too slow causes:", options: ["Narrow bead only", "Excessive buildup and undercut risk", "No fusion always", "Cold weld only"], correct: 1 },
    { type: "aptitude", q: "Inspect weld visually for:", options: ["Hair color", "Cracks, porosity, undercut", "Fabric grain", "CPU speed"], correct: 1 },
    { type: "aptitude", q: "PPE includes:", options: ["Sandals", "Leather gloves, helmet, apron", "Swim goggles only", "None"], correct: 1 },
  ],
}

const LABELS = ["Option A", "Option B", "Option C", "Option D"]

export function itemToRow(courseName, item) {
  const correct = LABELS[item.correct]
  const [a, b, c, d] = item.options
  return { courseName, type: item.type, q: item.q, a, b, c, d, correct }
}

export function allCourses() {
  return Object.keys(NAVS_QUESTION_BANK)
}

export function validateBank() {
  for (const [course, items] of Object.entries(NAVS_QUESTION_BANK)) {
    if (items.length !== 20) {
      throw new Error(`${course}: expected 20 questions, got ${items.length}`)
    }
    const pre = items.filter(i => i.type === "pre-skilled").length
    const apt = items.filter(i => i.type === "aptitude").length
    if (pre !== 10 || apt !== 10) {
      throw new Error(`${course}: expected 10 pre-skilled + 10 aptitude, got ${pre}+${apt}`)
    }
  }
}

validateBank()
